import face2 from '../assets/images/face-2.jpg'
export const dataCustomer = [
  {
    id: '1',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '2',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '3',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '4',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '5',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '6',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '7',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '8',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '9',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '10',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '11',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '12',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '13',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '14',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },

  {
    id: '15',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '16',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '17',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '18',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '1',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '2',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '3',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '4',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '5',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '6',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '7',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '8',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '9',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '10',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '11',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '12',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '13',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '14',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật Thịnh',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },

  {
    id: '15',
    avatar: face2,
    code: '1234',
    name: 'Lê huy ngọ',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '16',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  },
  {
    id: '17',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: true
  },
  {
    id: '18',
    avatar: face2,
    code: '1234',
    name: 'Nguyễn Hà Yến Nhi',
    email: 'ny@thinhpham.com',
    number: '0122323233',
    employee: 'Phạm Nhật',
    source: 'Landing Page',
    phase: 'Tiềm năng',
    isBusiness: false
  }
]
