export const PATH = Object.freeze({
  NOT_FOUND: "*",
  HOME: "/",
  SIGNIN: "/sign-in",
  SIGNUP: "/sign-up",
  REGISTER: "/register",
  ABOUT: "/about",
  PROFILE: "/profile",
  DASHBOARD: "/dashboard",
  CUSTOMER: "/customers",
  CUSTOMERDETAIL: "/customers/:id",
  EMPLOYEE: "/employees",
  EMPLOYEEDETAIL: "/employees/:id",
  BOARD: "/board",
  ACTIVITY: "/activities",
  ACTIVITYDETAIL: "/activities/:id",
  ORGANIZATION: "/organization",
  COMPLAIN: "/complains",
  COMPLAINDETAIL: "complains/:id",
  TABLE: "/tables",
  BILLING: "/billing",
});
